In [56]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import Markdown, display, HTML

# Fix the dying kernel problem (only a problem in some installations - you can remove it, if it works without it)
import os
os.environ['KMP_DUPLICATE_LIB_OK'] = 'True'

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


# Numpy tasks

For a detailed reference check out: https://numpy.org/doc/stable/reference/arrays.indexing.html.

**Task 1.** Calculate the sigmoid (logistic) function on every element of the following numpy array [0.3, 1.2, -1.4, 0.2, -0.1, 0.1, 0.8, -0.25] and print the last 5 elements. Use only vector operations.

In [10]:
vector = np.array([0.3, 1.2, -1.4, 0.2, -0.1, 0.1, 0.8, -0.25])
sigmoid = 1/(1 + np.exp(-vector))
print(sigmoid[-5::])

[0.549834   0.47502081 0.52497919 0.68997448 0.4378235 ]


**Task 2.** Calculate the dot product of the following two vectors:<br/>
$x = [3, 1, 4, 2, 6, 1, 4, 8]$<br/>
$y = [5, 2, 3, 12, 2, 4, 17, 11]$<br/>
a) by using element-wise mutliplication and np.sum,<br/>
b) by using np.dot,<br/>
b) by using np.matmul and transposition (x.T).

In [5]:
x = np.array([3, 1, 4, 2, 6, 1, 4, 8])
y = np.array([5, 2, 3, 12, 2, 4, 17, 11])

# a)
print(np.sum(x * y))

# b)
              
print(np.dot(x, y))
              
# c)

print(np.matmul(x, y))


225
225
[[225]]


**Task 3.** Calculate value of the logistic model<br/>
$$y = \frac{1}{1 + e^{-x_0 \theta_0 - \ldots - x_9 \theta_9 - \theta_{10}}}$$
for<br/>
$x = [1.2, 2.3, 3.4, -0.7, 4.2, 2.7, -0.5, 1.4, -3.3, 0.2]$<br/>
$\theta = [2.7, 0.33, -2.12, -1.73, 2.9, -5.8, -0.9, 12.11, 3.43, -0.5, -1.65]$<br/>
and print the result. Use only vector operations.

In [7]:
x = np.array([1.2,2.3,3.4,-0.7,4.2,2.7,-0.5,1.4,-3.3,0.2])
thetas = np.array([2.7,0.33,-2.12,-1.73,2.9,-5.8,-0.9,12.11,3.43,-0.5,-1.65])

exp_sum = np.sum(np.multiply(-x, thetas[:-1])) - thetas[-1]

logistic_model = 1 / (1 + np.exp(exp_sum))
print(logistic_model)

0.2417699832615572


**Task 4.** Calculate value of the multivariate linear regression model<br/>
$$y = A x + B$$
for<br/>
$A = \begin{bmatrix} 1 & 2 & 1 \\ 3 & 0 & 1 \end{bmatrix}$<br/>
$B = \begin{bmatrix} 0.2 \\ 0.3 \end{bmatrix}$<br/>
$x = [1, 2, 3]^T$<br/>
and print the result. Use only vector and matrix operations.

In [15]:
A = np.array([1, 2, 1, 3, 0, 1]).reshape(2, 3)
B = np.array([0.2, 0.3]).reshape(2, 1)
x = np.array([1, 2, 3])[np.newaxis]
y = np.dot(A, np.transpose(x)) + B
print(y)

[[8.2]
 [6.3]]


# Pandas

## Load datasets

- Steam (https://www.kaggle.com/tamber/steam-video-games)

- MovieLens (https://grouplens.org/datasets/movielens/)

In [57]:
steam_df = pd.read_csv(os.path.join("data", "steam", "steam-200k.csv"), 
                       names=['user-id', 'game-title', 'behavior-name', 'value', 'zero'])

ml_ratings_df = pd.read_csv(os.path.join("data", "movielens_small", "ratings.csv"))
ml_movies_df = pd.read_csv(os.path.join("data", "movielens_small", "movies.csv"))

## Merge both MovieLens DataFrames into one

In [58]:
ml_df = pd.merge(ml_ratings_df, ml_movies_df, on='movieId')
ml_df.head(10)
steam_df.head(10)

user-id                  game-title behavior-name  value  zero
0  151603712  The Elder Scrolls V Skyrim      purchase    1.0     0
1  151603712  The Elder Scrolls V Skyrim          play  273.0     0
2  151603712                   Fallout 4      purchase    1.0     0
3  151603712                   Fallout 4          play   87.0     0
4  151603712                       Spore      purchase    1.0     0
5  151603712                       Spore          play   14.9     0
6  151603712           Fallout New Vegas      purchase    1.0     0
7  151603712           Fallout New Vegas          play   12.1     0
8  151603712               Left 4 Dead 2      purchase    1.0     0
9  151603712               Left 4 Dead 2          play    8.9     0

## Pandas tasks - Steam dataset

**Task 5.** How many people made a purchase in the Steam dataset? Remember that a person could buy many games, but you need to count every person once.

In [114]:
display(steam_df.loc[steam_df['behavior-name'] == 'purchase']['user-id'].nunique())

12393

**Task 6.** How many people made a purchase of "The Elder Scrolls V Skyrim"?

In [115]:
display(steam_df.loc[steam_df['game-title'] == 'The Elder Scrolls V Skyrim']['user-id'].nunique())

717

**Task 7.** How many purchases people made on average?

In [19]:
purchase_df = steam_df.loc[steam_df['behavior-name'] == 'purchase'].groupby('user-id')
display(purchase_df['user-id'].value_counts().mean())

10.45033486645687

**Task 8.** Who bought the most games?

In [26]:
display(purchase_df.sum().sort_values(by='value', ascending=False).reset_index().head(1)['user-id'].values[0])

62990992

**Task 9.** How many hours on average people played in "The Elder Scrolls V Skyrim"?

In [134]:
play_df = steam_df.loc[(steam_df['behavior-name'] == 'play') & (steam_df['game-title'] == 'The Elder Scrolls V Skyrim')].copy()
display(play_df.value.mean())

104.71093057607091

**Task 10.** Which games were played the most (in terms of the number of hours played)? Print the first 10 titles and respective numbers of hours.

In [14]:
play_df = steam_df.loc[steam_df['behavior-name'] == 'play'].groupby('game-title')
summed_play_df = play_df.sum().sort_values(by='value', ascending=False).reset_index()
display(summed_play_df[['game-title', 'value']].head(10))

game-title     value
0                                       Dota 2  981684.6
1              Counter-Strike Global Offensive  322771.6
2                              Team Fortress 2  173673.3
3                               Counter-Strike  134261.1
4                   Sid Meier's Civilization V   99821.3
5                        Counter-Strike Source   96075.5
6                   The Elder Scrolls V Skyrim   70889.3
7                                  Garry's Mod   49725.3
8  Call of Duty Modern Warfare 2 - Multiplayer   42009.9
9                                Left 4 Dead 2   33596.7

**Task 11.** Which games are the most consistently played (in terms of the average number of hours played)? Print the first 10 titles and respective numbers of hours.

In [146]:
summed_play_df = play_df.mean().sort_values(by='value', ascending=False).reset_index()
display(summed_play_df[['game-title', 'value']].head(10))

game-title        value
0            Eastside Hockey Manager  1295.000000
1  Baldur's Gate II Enhanced Edition   475.255556
2                    FIFA Manager 09   411.000000
3                          Perpetuum   400.975000
4              Football Manager 2014   391.984615
5              Football Manager 2012   390.453165
6              Football Manager 2010   375.048571
7              Football Manager 2011   365.703226
8                  Freaking Meatbags   331.000000
9        Out of the Park Baseball 16   330.400000

**Task 12\*\*.** Fix the above for the fact that 0 hours played is not listed, but only a purchase is recorded in such a case.

In [ ]:
# Write your code here

**Task 13.** Apply the sigmoid function
$$f(x) = \frac{1}{1 + e^{-\frac{1}{100}x}}$$
to hours played and print the first 10 rows from the entire Steam dataset after this change.

In [30]:
def sigmoid(x):
    return 1 / (1 + np.exp(-(1/100) * x))

df = steam_df.copy()
df.value = np.where(
    df["behavior-name"] == 'play', 
    sigmoid(df['value']), 
    df['value']
)
print(df.head(10))

          user-id                  game-title behavior-name     value  zero
0       151603712  The Elder Scrolls V Skyrim      purchase  1.000000     0
1       151603712  The Elder Scrolls V Skyrim          play  0.938774     0
2       151603712                   Fallout 4      purchase  1.000000     0
3       151603712                   Fallout 4          play  0.704746     0
4       151603712                       Spore      purchase  1.000000     0
...           ...                         ...           ...       ...   ...
199995  128470551                 Titan Souls          play  0.503750     0
199996  128470551  Grand Theft Auto Vice City      purchase  1.000000     0
199997  128470551  Grand Theft Auto Vice City          play  0.503750     0
199998  128470551                        RUSH      purchase  1.000000     0
199999  128470551                        RUSH          play  0.503500     0

[200000 rows x 5 columns]


## Pandas tasks - MovieLens dataset

**Task 14\*.** Calculate popularity (by the number of users who watched a movie) of all genres. Print a DataFrame with two columns: genre, n_users, where n_users contains the number of users who watched a given genre. Sort all genres in descending order.

In [ ]:
# Write your code here

**Task 15\*.** Calculate average rating for all genres. Print a DataFrame with two columns: genre, rating, where rating contains the average rating for a given genre. Sort all genres in descending order.

In [ ]:
# Write your code here

**Task 17.** Calculate each movie rating bias (deviation from the mean of all movies average rating). Print first 10 in the form: title, average rating, bias.

In [35]:
ml_df_mean = ml_df[['title', 'rating']].groupby('title').mean()
avg_rating = ml_df['rating'].mean()

ml_df_mean = ml_df_mean.rename(columns = {'rating': 'average_rating'})
ml_df_mean['bias'] = ml_df_mean - avg_rating 
display(ml_df_mean.head(10).reset_index())


title  average_rating      bias
0                               '71 (2014)        4.000000  0.498443
1  'Hellboy': The Seeds of Creation (2004)        4.000000  0.498443
2                   'Round Midnight (1986)        3.500000 -0.001557
3                      'Salem's Lot (2004)        5.000000  1.498443
4                'Til There Was You (1997)        4.000000  0.498443
5          'Tis the Season for Love (2015)        1.500000 -2.001557
6                       'burbs, The (1989)        3.176471 -0.325086
7                     'night Mother (1986)        3.000000 -0.501557
8              (500) Days of Summer (2009)        3.666667  0.165110
9           *batteries not included (1987)        3.285714 -0.215843

**Task 17.** Calculate each user rating bias (deviation from the mean of all users average rating). Print first 10 in the form: user_id, average rating, bias.

In [38]:
# def calculate_values(user_id):
#     return user_id, ml_df[ml_df['userId'] == user_id].rating.mean(), ml_df[ml_df['userId'] == user_id].rating.mean() - ml_df.rating.mean()

# user_ids = sorted(ml_df['userId'].unique())
# df = pd.DataFrame([calculate_values(user_id) for user_id in user_ids], columns=['userId', 'average_rating', 'bias'])
# print(df.head(10))

ml_df_mean = ml_df[['userId', 'rating']].groupby('userId').mean()
avg_rating = ml_df['rating'].mean()

ml_df_mean = ml_df_mean.rename(columns = {'rating': 'average_rating'})
ml_df_mean['bias'] = ml_df_mean - avg_rating 
display(ml_df_mean.head(10).reset_index())

userId  average_rating      bias
0       1        4.366379  0.864822
1       2        3.948276  0.446719
2       3        2.435897 -1.065660
3       4        3.555556  0.053999
4       5        3.636364  0.134807
5       6        3.493631 -0.007926
6       7        3.230263 -0.271294
7       8        3.574468  0.072911
8       9        3.260870 -0.240687
9      10        3.278571 -0.222986

**Task 18.** Randomly choose 10 movies and 10 users and print their interaction matrix in the form of a DataFrame with user_id as index and movie titles as columns. You can iterate over the DataFrame in this task.

In [47]:
user_ids = ml_df['userId'].unique()
movie_ids = ml_df['movieId'].unique()
rng = np.random.RandomState(seed=4321)
user_ids = sorted(list(rng.choice(user_ids, size=10)))
movie_ids = sorted(list(rng.choice(movie_ids, size=10)))
movies = {
    movie_id: ml_df[ml_df['movieId'] == movie_id].iloc[0].title 
        for movie_id in movie_ids
}

df = pd.DataFrame(0.0, index=user_ids, columns=movies.values())

for user_id in user_ids:
    for movie_id in movie_ids:
        if(ml_df[(ml_df['userId'] == user_id) & (ml_df['movieId'] == movie_id)].empty == False):
            df.at[user_id, movies[movie_id]] = 1.0
           
display(df)

Father of the Bride (1950)  Matrix, The (1999)  Howards End (1992)  \
11                          0.0                 0.0                 0.0   
277                         0.0                 0.0                 0.0   
286                         0.0                 1.0                 0.0   
357                         0.0                 0.0                 0.0   
414                         0.0                 1.0                 0.0   
428                         0.0                 1.0                 0.0   
470                         0.0                 0.0                 0.0   
487                         0.0                 1.0                 0.0   
543                         0.0                 1.0                 0.0   
544                         0.0                 0.0                 0.0   

     Thirteen Conversations About One Thing (a.k.a. 13 Conversations) (2001)  \
11                                                 0.0                         
277                                                0.0                         
286                                                0.0                         
357                                                0.0                         
414                                                1.0                         
428                                                0.0                         
470                                                0.0                         
487                                                0.0                         
543                                                0.0                         
544                                                0.0                         

     It Runs in the Family (2003)  I Love You to Death (1990)  \
11                            0.0                         0.0   
277                           0.0                         0.0   
286                           0.0                         0.0   
357                           0.0                         0.0   
414                           0.0                         0.0   
428                           0.0                         0.0   
470                           0.0                         0.0   
487                           0.0                         0.0   
543                           0.0                         0.0   
544                           0.0                         0.0   

     Bedazzled (1967)  I Don't Know How She Does It (2011)  \
11                0.0                                  0.0   
277               0.0                                  0.0   
286               0.0                                  0.0   
357               0.0                                  0.0   
414               0.0                                  0.0   
428               0.0                                  0.0   
470               0.0                                  0.0   
487               0.0                                  0.0   
543               0.0                                  0.0   
544               0.0                                  0.0   

     Wind Rises, The (Kaze tachinu) (2013)  Night Guards (2016)  
11                                     0.0                  0.0  
277                                    0.0                  0.0  
286                                    0.0                  0.0  
357                                    0.0                  0.0  
414                                    0.0                  0.0  
428                                    0.0                  0.0  
470                                    0.0                  0.0  
487                                    0.0                  0.0  
543                                    0.0                  0.0  
544                                    0.0                  0.0

## Pandas + numpy tasks

**Task 19.** Create the entire interaction matrix for the MovieLens dataset. Print the submatrix of first 10 rows and 10 columns.

In [55]:
df = ml_df.pivot_table(index='userId', columns='movieId', aggfunc=len, fill_value=0)
# print(np.array(df.iloc[:10,:10]))

k = np.array(df.iloc[:10,:10])
k[k == 1] = 5
print(k)
print('----')
print(k[:, 1])

[[5 0 5 0 0 5 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [5 0 0 0 0 0 0 0 0 0]
 [0 5 5 5 5 5 5 5 0 5]
 [5 0 0 0 0 0 0 0 0 0]
 [0 5 0 0 0 0 0 0 0 5]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
----
[0 0 0 0 0 5 0 5 0 0]


**Task 20.** Calculate the matrix of size (n_users, n_users) where at position (i, j) there is the number of movies watched both by user i and user j. Print the submatrix of first 10 rows and 10 columns.

In [ ]:
interaction_matrix = np.zeros(shape=(ml_df['userId'].max() + 1, ml_df['movieId'].max() + 1))
for ids, row in ml_df.iterrows():
    interaction_matrix[row['userId']][row['movieId']] = 1
n_watched_movies = np.matmul(interaction_matrix, interaction_matrix.T)

print(n_watched_movies[:10, :10])

**Task 21.** Calculate the matrix of size (n_items, n_items) where at position (i, j) there is the number of users who watched both movie i and movie j. To prevent hanging your computer because of RAM shortage use only the first 1000 items. Print the submatrix of first 10 rows and 10 columns.

In [ ]:
# Write your code here